name: MaSuiteWarpsBridge
main: fi.matiaspaavilainen.masuitewarps.MaSuiteWarps
version: 1.4
author: Masagameplay
commands:
  warp:
    description: Warps player to specified location
    aliases: [warpto]
  setwarp:
    description: Creates warp point
    aliases: [warpset, createwarp]